[package]
name = "img2bf"
version = "0.1.0"
authors = ["Matej <dobrakmato@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23.14"
intel_tex = "0.1.4"
structopt = "0.3.22"
bf = { path = "../bf" }
core = { path = "../core" }