[workspace]
members = [
    "asset-server",
    "core",
    "bf",
    "img2bf",
    "obj2bf",
    "bfinfo",
    "matcomp",
    "renderer"
]

[profile.release]
debug = true
lto = false
incremental = true
codegen-units = 256
debug-assertions = true