[package]
name = "obj2bf"
version = "0.1.0"
authors = ["Matej <dobrakmato@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.22"
wavefront_obj = "10.0.0"
byteorder = "1.3.4"
ordered-float = "2.1.1"
fbxcel-dom = "0.0.6"
bf = { path = "../bf" }
core = { path = "../core" }