[package]
name = "obj2bf"
version = "0.1.0"
authors = ["Matej <dobrakmato@gmail.com>"]
edition = "2018"


[dependencies]
lz4 = "1.23.1"
clap = "2.33.0"
zerocopy = "0.2.8"
wavefront_obj = "7.0.0"
matches = "0.1.8"
bf = { path = "../bf" }