[package]
name = "obj2bf"
version = "0.1.0"
authors = ["Matej <dobrakmato@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.11"
wavefront_obj = "7.0.0"
byteorder = "1.3.2"
bf = { path = "../bf" }
core = { path = "../core" }