[package]
name = "bf"
version = "0.1.0"
authors = ["Matej <dobrakmato@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.1"
serde = { version = "1.0.104", features = ["derive"] }
serde_derive = "1.0.104"
lz4 = "1.23.1"

[dev-dependencies]
