[package]
name = "renderer"
version = "0.1.0"
authors = ["Matej <dobrakmato@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = "0.17.0"
safe-transmute = "0.11.0-rc.2"
bf = { path = "../bf" }
log = "0.4.8"
simple_logger = "1.4.0"
vulkano = "0.17.0"
vulkano-shaders = "0.17.0"
vulkano-win = "0.17.0"
winit = "0.21.0"