[package]
name = "renderer"
version = "0.1.0"
authors = ["Matej <dobrakmato@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "1.3.1"
crossbeam = "0.7.3"
smallvec = "1.2.0"
cgmath = {version = "0.17.0", features = ['serde'] }
safe-transmute = "0.11.0-rc.2"
bf = { path = "../bf" }
log = "0.4.8"
simple_logger = "1.4.0"
serde = "1.0.104"
serde_json = "1.0.48"
vulkano = "0.17.0"
vulkano-shaders = "0.17.0"
vulkano-win = "0.17.0"
winit = "0.22.0"