[package]
name = "matcomp"
version = "0.1.0"
authors = ["Matej <dobrakmato@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.8.2", features = ["serde"] }
structopt = "0.3.21"
bf = { path = "../bf" }